# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Custom vars
version:          2.1.0

github:           metadata

repository:       mcebey/mcebey.github.io
userdisqus:       username

# Setup
author:
  name:           "mcebey"
  url:            https://twitter.com/mcebeyf
  twitter:        mcebeyf

paginate:         10

title:            "Jekyll blog test"
tagline:          "testing ahother blog system"
description:      "jeykyll searching hyde"
locale:           es_es
encoding:         utf-8
url:              https://mcebey.github.io
baseurl:          https://mcebey.github.io/  
google_analytics: UA-XXXXXXXXX-X